In [1]:
import pandas as pd
import winnamax
import betclic
import netbet
import pmu
import zebet
from difflib import SequenceMatcher
import numpy as np

def similar(a,b):
    res = []
    for i in range(len(b)) :
        res.append(SequenceMatcher(None,a,b[i]).ratio())
    return np.argmax(res)

competition = {'sport': 'football', 'competition': 'ligue1'}

win = winnamax.into_a_pd(competition)
net= netbet.into_a_pd(competition)
pm = pmu.into_a_pd(competition)
zeb = zebet.into_a_pd(competition)
bet = betclic.into_a_pd(competition)

In [2]:
net

,team1,team2,odd of team 1 winning,odds of equality,odd of team 2 winning,key
0,Strasbourg,Lyon,2.55,3.45,2.35,StrasbourgvLyon
1,PSG,Lorient,1.11,7.50,13.00,PSGvLorient
2,Marseille,Reims,1.48,4.00,5.30,MarseillevReims
3,Rennes,Metz,1.34,4.50,7.00,RennesvMetz
4,Nice,Lille,2.85,3.35,2.17,NicevLille
5,Clermont,Monaco,3.40,3.55,1.88,ClermontvMonaco
6,Nantes,Toulouse,2.17,3.25,2.92,NantesvToulouse
7,Brest,Lens,4.00,3.50,1.73,BrestvLens
8,Montpellier,LeHavre,1.82,3.35,3.85,MontpelliervLeHavre

In [3]:
win

,team1,team2,odd of team 1 winning,odds of equality,odd of team 2 winning,key
0,ParisSG,Lorient,1.15,6.25,11.00,ParisSGvLorient
1,Clermont,Monaco,3.30,3.45,1.90,ClermontvMonaco
2,Strasbourg,Lyon,2.50,3.40,2.35,StrasbourgvLyon
3,Rennes,Metz,1.38,4.20,6.50,RennesvMetz
4,Marseille,Reims,1.50,3.95,5.10,MarseillevReims
5,Nice,Lille,2.75,3.30,2.20,NicevLille
6,Nantes,Toulouse,2.20,3.20,2.80,NantesvToulouse
7,Montpellier,LeHavre,1.90,3.10,3.65,MontpelliervLeHavre
8,Brest,Lens,3.95,3.40,1.76,BrestvLens

In [4]:
bet

,team1,team2,odd of team 1 winning,odds of equality,odd of team 2 winning,key
0,Rennes,Metz,1.39,4.25,6.50,RennesvMetz
1,Clermont,Monaco,3.30,3.50,1.92,ClermontvMonaco
2,Strasbourg,Lyon,2.52,3.40,2.38,StrasbourgvLyon
3,Marseille,Reims,1.50,3.95,5.15,MarseillevReims
4,ParisSG,Lorient,1.16,6.80,11.00,ParisSGvLorient
5,Nantes,Toulouse,2.25,3.20,2.82,NantesvToulouse
6,Nice,Lille,2.80,3.30,2.22,NicevLille
7,Montpellier,LeHavre,1.85,3.30,3.75,MontpelliervLeHavre
8,Brest,Lens,4.00,3.40,1.77,BrestvLens

In [5]:
zeb

,team1,team2,odd of team 1 winning,odds of equality,odd of team 2 winning,key
0,Clermont,Monaco,3.30,3.50,1.82,ClermontvMonaco
1,Rennes,Metz,1.31,4.40,6.75,RennesvMetz
2,Strasbourg,Lyon,2.50,3.40,2.27,StrasbourgvLyon
3,Marseille,Reims,1.43,4.00,5.30,MarseillevReims
4,ParisSG,Lorient,1.09,7.25,13.00,ParisSGvLorient
5,Nantes,Toulouse,2.15,3.20,2.82,NantesvToulouse
6,Nice,Lille,2.77,3.30,2.10,NicevLille
7,Montpellier,LeHavre,1.78,3.25,3.70,MontpelliervLeHavre
8,Brest,Lens,4.00,3.45,1.68,BrestvLens

In [6]:
import pandas as pd
import winnamax
import betclic
import netbet
import pmu
import zebet
from difflib import SequenceMatcher
import numpy as np

def similar(a,b):
    res = []
    for i in range(len(b)) :
        res.append(SequenceMatcher(None,a,b[i]).ratio())
    return np.argmax(res)

def similar_ratio(a,b) :
    res = []
    for i in range(len(b)) :
        res.append(SequenceMatcher(None,a,b[i]).ratio())
    return max(res)

competitionn = {'sport': 'football', 'competition': 'premier-league'}
def merge_results(competition):
    matches = []
    win = winnamax.into_a_pd(competition)
    net= netbet.into_a_pd(competition)
    pm = pmu.into_a_pd(competition)
    zeb = zebet.into_a_pd(competition)
    bet = betclic.into_a_pd(competition)
    long = min([len(win),len(net),len(pm),len(zeb),len(bet)])
    for i in range(long) :
        concordance_netbet = similar(win['key'][i],net['key'])
        ratio_netbet = similar_ratio(win['key'][i],net['key'])

        conc_pmu = similar(win['key'][i],pm['key'])
        ratio_pmu = similar_ratio(win['key'][i],pm['key'])

        conc_zebet = similar(win['key'][i],zeb['key'])
        ratio_zebet = similar_ratio(win['key'][i],zeb['key'])

        conc_betclic = similar(win['key'][i],bet['key'])
        ratio_betclic = similar_ratio(win['key'][i],bet['key'])

        if (ratio_netbet < 0.8 or ratio_pmu<0.8 or ratio_zebet<0.8 or ratio_betclic < 0.8) :
            continue
    
        match = [win[i:i+1],net[concordance_netbet:concordance_netbet+1],pm[conc_pmu:conc_pmu+1],zeb[conc_zebet:conc_zebet+1],bet[conc_betclic:conc_betclic+1]]
        match = pd.concat(match)
        match['site'] = ['winnamax','netbet','pmu','zebet','betclic']
        matches.append(match)
    return matches

A = merge_results(competitionn)

In [8]:
A

[]

In [9]:
resu = []
a = A[0]['odd of team 1 winning'].values
c = A[0]['odd of team 2 winning'].values
b = A[0]['odds of equality '].values
site = A[0]['site'].values
for i in range(len(A[0])) :
    for j in range(len(A[0])) :
        for k in range(len(A[0])) :
            if i==j and i == k :
                continue
            else :
                resu.append(((a[i],b[j],c[k]),(site[i],site[j],site[k])))

resu

IndexError: list index out of range

In [9]:
resu[0][1][2]

'netbet'

In [10]:
import log 
log.log("test")

NameError: name 'filename' is not defined

In [ ]:
import sqlite3
conn = sqlite3.connect('found_opp.db')

# Create a cursor object to execute SQL commands
cursor = conn.cursor()

# Execute a SELECT statement to retrieve all rows from the table
cursor.execute("SELECT * FROM history_opportunities_foot")

# Fetch all the rows and print them
rows = cursor.fetchall()
for row in rows:
    print(row)

# Close the database connection
conn.close()

OperationalError: no such table: history_opportunities_foot